# Generated by Django 3.1.1 on 2020-09-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customer_usergroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCatagory',
        ),
    ]
