# Generated by Django 3.1.1 on 2020-09-13 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_delete_subcatagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='usergroup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.usergroup'),
        ),
    ]
