# Generated by Django 3.0.8 on 2020-08-21 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200821_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_right_view',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
