# Generated by Django 3.1.1 on 2020-09-13 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200913_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='usergroup',
        ),
        migrations.DeleteModel(
            name='Usergroup',
        ),
    ]
