# Generated by Django 3.1 on 2020-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
