# Generated by Django 3.1 on 2020-08-29 07:46

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
