# Generated by Django 3.1.1 on 2020-09-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200914_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
