# Generated by Django 3.1.1 on 2020-09-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200914_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
